name: WeatherApp CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: STEP 1 -> Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh
    - name: Log in to Heroku
      run: heroku login -i
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    - name: Set Heroku Git remote
      run: heroku git:remote -a weatherapp-heroku
    - name: STEP 2 -> Build with Maven
      run: mvn --file ./Cityweather/pom.xml clean install
    - name: STEP 3 -> Test with Maven
      run: mvn --file ./Cityweather/pom.xml test
    - name: Deploy to Heroku
      run: mvn heroku:deploy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
