name: WeatherApp CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Debug HEROKU_API_KEY
      run: echo $HEROKU_API_KEY
    - name: Build with Maven
      run: mvn --file ./pom.xml clean install
    - name: Move generated .war file
      run: mv target/Cityweather-1.0.war .
    - name: Test with Maven
      run: mvn --file ./pom.xml test
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "weatherapp-kalilo"
        heroku_email: "kalilo555@usp.br"
        war_heroku: "Cityweather-1.0.war"
